services:
  apispotify:
    image: richkelman/tweezer-api-spotify:latest
    depends_on:
      - barramento
    build: 
      context: ./apiSpotify
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    networks:
      - tweezer_net

  barramento:
    image: richkelman/tweezer-barramento:latest
    build: 
      context: ./barramentoDeEventos
      dockerfile: ./Dockerfile
    ports:
      - "10000:10000"
    networks:
      - tweezer_net

  frontend:
    image: richkelman/tweezer-frontend:latest
    depends_on:
      - apispotify
      - usuarios
      - posts
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - tweezer_net

  posts:
    image: richkelman/tweezer-posts:latest
    depends_on:
      - barramento
    build: 
      context: ./posts
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    networks:
      - tweezer_net

  usuarios:
    image: richkelman/tweezer-usuarios:latest
    build: 
      context: ./usuarios
      dockerfile: ./Dockerfile
    depends_on:
      - barramento
    ports:
      - "5001:5001"
    networks:
      - tweezer_net

networks:
  tweezer_net:
    driver: bridge
