services:
   apispotify:
      image: richkelman/tweezer-api-spotify:v2
      depends_on:
         - barramento
      build:
         context: ./apiSpotify
         dockerfile: ./Dockerfile
      # ports:
      #    - "8888:8888"
      networks:
         - tweezer_net

   barramento:
      image: richkelman/tweezer-barramento:v2
      build:
         context: ./barramentoDeEventos
         dockerfile: ./Dockerfile
      # ports:
      #    - "10000:10000"
      networks:
         - tweezer_net

   frontend:
      image: richkelman/tweezer-frontend:v2
      depends_on:
         - apispotify
         - usuarios
         - posts
      build:
         context: ./frontend
         dockerfile: ./Dockerfile
      # ports:
      #    - "3000:3000"
      networks:
         - tweezer_net

   posts:
      image: richkelman/tweezer-posts:v2
      depends_on:
         - barramento
      build:
         context: ./posts
         dockerfile: ./Dockerfile
      # ports:
      #    - "5002:5002"
      networks:
         - tweezer_net

   usuarios:
      image: richkelman/tweezer-usuarios:v2
      build:
         context: ./usuarios
         dockerfile: ./Dockerfile
      depends_on:
         - barramento
      # ports:
      #    - "5001:5001"
      networks:
         - tweezer_net

   nginx:
      image: richkelman/tweezer-nginx:v2
      build:
         context: ./nginx
         dockerfile: ./Dockerfile
      depends_on:
         - apispotify
      ports:
         - "80:80"
      networks:
         - tweezer_net

networks:
   tweezer_net:
      driver: bridge
