# Use a imagem base do nginx
FROM nginx:1.25-alpine3.18-perl

# Copie o arquivo de configuração para o diretório de configuração do nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Exponha a porta 80
EXPOSE 80
